
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT1 = 5;
  public static final int PUNTOYCOMA = 15;
  public static final int ABRECORCHETE = 16;
  public static final int ENTERO = 3;
  public static final int RESTA = 23;
  public static final int PARENIZQ = 20;
  public static final int LLAVEDER = 19;
  public static final int PRI = 8;
  public static final int FOR = 35;
  public static final int PUB = 7;
  public static final int IDENTIFICADOR = 2;
  public static final int IGUAL = 30;
  public static final int CHAR1 = 6;
  public static final int ASIGNA = 31;
  public static final int SUMA = 22;
  public static final int IF = 34;
  public static final int ABSTRACT = 41;
  public static final int BOOLEAN = 40;
  public static final int VOI = 9;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int MAYOROIGUAL = 32;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int CADENA = 4;
  public static final int MODULO = 27;
  public static final int NEGACION = 14;
  public static final int MENOR = 29;
  public static final int CIERRACORCHETE = 17;
  public static final int BREAK = 38;
  public static final int PARENDER = 21;
  public static final int MENOROIGUAL = 33;
  public static final int MAYOR = 28;
  public static final int POTENCIA = 26;
  public static final int ELSE = 37;
  public static final int LLAVEIZQ = 18;
  public static final int CONJUNCION = 12;
  public static final int DISYUNCION = 11;
  public static final int DIVISION = 25;
  public static final int ELIF = 36;
  public static final int PRINT = 10;
  public static final int MULTIPLICACION = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "ENTERO",
  "CADENA",
  "INT1",
  "CHAR1",
  "PUB",
  "PRI",
  "VOI",
  "PRINT",
  "DISYUNCION",
  "CONJUNCION",
  "COMA",
  "NEGACION",
  "PUNTOYCOMA",
  "ABRECORCHETE",
  "CIERRACORCHETE",
  "LLAVEIZQ",
  "LLAVEDER",
  "PARENIZQ",
  "PARENDER",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "ASIGNA",
  "MAYOROIGUAL",
  "MENOROIGUAL",
  "IF",
  "FOR",
  "ELIF",
  "ELSE",
  "BREAK",
  "RETURN",
  "BOOLEAN",
  "ABSTRACT"
  };
}

